### ISSUE TITLE
Issue in generating access_token 

### ISSUE THREAD

**Issue by tradewithmadhan** [FyersDev/Fyers-Trading-APIs-Sample-Code#24]
Issue in generating access_token 

{'s': 'error', 'code': -371, 'message': 'Please provide sha256 hash of appId and app secret'}  

Using below code to generate access_token ... Pls check 

```
moduleName = "getAccessToken"
"""
    1.We need to first install fyers-apiv2(can be installed as 'pip install fyers-apiv2)
    2.We then need to import accesToken module from fyers_api directory(as done below)
    3.We also need to import webbrowser to preform an action while generating authcode
"""

from fyers_api import accessToken

import webbrowser


def getauthToken(appId, redirect_uri):
    functionName = "getauthToken"
    """
        :param app_id: "XXXXXXXXXXX"
        :param redirect_url: "https://XXXXXX.com"
		 1. This function open this url in the browser.
		 2. This will ask you to login and will ask you to approve the app if it is not approved already.
		 3. Once that is done, it will redirect to a url (added while app creation) with the auth_code. The url will look like
		    https://www.google.com/?auth_code=eyJ0eXAiOiXXXXXGciOiJIUzI1NiJ9.eyXXXXXXXXXXXXXInN1YiI6ImF1dGhDb2XXXXXXXXXXXXXXXXXX2lkIjoiQjhQV0xWSDhUNiIsImlzcyI6ImFwaS5sb2dpbi5meWVycy5pbiIsImF1ZCI6WyJ4OjAiLCJ4OjEiLCJ4OjIiXSwidXVpZCI6ImZhOGNhYjE3ZWU4OTQzMGRhZjA1YWUxNDI2YWVkYzI4IiwiaXBBZGRyIjoiMjIzLjIzMy40Mi40NiIsImRpc3BsYXlfbmFtZSI6IkRQMDA0MDQiLCJpYXQiOjE1OTM1ODYzNzEsIm5iZiI6MTU5MzU4NjM3MX0.IMJHzQGHQgyXt_XN0AgDrMN1keR4qolFFKO6cyXTnTg&user_id=DP00404
		 4. You have to take the auth_code from the url and use that token in your generate_access_token function.
	"""
    response_type="code"
    grant_type="authorization_code"
    # creating an instance appSession to generate the auth code by passing app id and redirect url as parameter
    appSession = accessToken.SessionModel(client_id=appId,redirect_uri=redirect_uri,response_type=response_type, grant_type=grant_type,state="state",scope="",nonce="")

    # The variable `generateTokenUrl` will have a url like https://uat-api.fyers.in/api/dev/generate-authcode?appId=B8PXXXH8T6&redirectUrl=https%3A%2F%2Fgoogle.com
    generateTokenUrl = appSession.generate_authcode()

    # This command is used to open the url in default system brower
    webbrowser.open(generateTokenUrl, new=1)


def generate_access_token(auth_code, appId, secret_key):
    functionName = "generate_access_token"
    """
	:param auth_code: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1OTM1ODY2NzEsInN1YiI6ImF1dGhDb2RlIiwiYXBwX2lkIjoiQjhQV0xWSDhUNiIsImlzcyI6ImFwaS5sb2dpbi5meWVycy5pbiIsImF1ZCI6WyJ4OjAiLCJ4OjEiLCJ4OjIiXSwidXXXXXXXXXXXYjE3ZWU4OTQzMGRhZjA1YWUxNDI2YWVkYzI4IiwiaXBBZGRyIjoiMjIzLjIzMy40Mi40NiIsImRpc3BsYXlfbmFtZSI6IkRQMDA0MDQiLCJpYXQiOjE1OTM1ODYzNzEsIm5iZiI6MTU5MzU4NjM3MX0.IMJHzQGHQgyXt_XN0AgDrMN1keR4qolFFKO6cyXTnTg"
	:param app_id: "B8PXXXXXXX"
	:param secret_key: "XXXXXXKGN0"
	:param redirect_url: "https://XXXXXX.com"
	:return: access_token: "eyJ0eXAiOiJKV1QiLCXXXX1NiJ9.eyJpYXXXXXXXXXXMsIm5iZiI6MTU5MzU4ODM3MywiZXhwIjoxNTkzNjQ5ODEzLCJpc3MiOiJhcGkuZnllcnMuaW4iLCJzdWIiOiJhY2Nlc3MiLCJhdWQiOiJ4OjAseDoxLHg6MiIsImF0X2hhc2giOiJnQUFBQUFCZV9EcVZIZExMMTAzTVpVN1NYSkZfR2p5R3hidzMtTVVhb0VEMGI0QUVvNjFsR24tREY2OFU5cXhuNzd0UXVoOVVJalYtNm9MVXhINVFfWE1WTEJfRXpROGV2clJmUzlNUXB0Y2J5c2ltN1drWllZTT0iLCJkaXNwbGF5X25hbWUiOiJQSVlVU0ggUkFKRU5EUkEgS0FQU0UiLCJmeV9pZCI6IkRQMDA0MDQifQ.cAfrj2TxAyb8A_9DfiCb1hLIZg_mH-xvP3Ybnj3a4AE"

	1.this function takes the param and return the access_token
	2.the access_token created will be used further .(in fyersModel)]
	3. one can get the auth_code from the url generated by getauthToken function (from auth_code= ..... &user_Id=xxxxxx before &)
	"""
    # creating an instance appSession by passing app id,secret key and redirect url as parameter
    appSession = accessToken.SessionModel(client_id=appId, secret_key=secret_key,grant_type="authorization_code")

    # we need to pass the auth code in set_token method
    appSession.set_token(auth_code)
    # generate_token function will return us the access token and we store in variable "access_token"
    access_token = appSession.generate_token()
    return access_token


def main():
    """
    Starting Steps.
    1.We first need to uncomment the function getauthToken(appId, redirect_url).
    2.We need to make sure generate_access_token(auth_code, appId, app_secret, redirect_url) func is commented.
    3.We need to run this module code once passing the parameters to getauthToken(appId, redirect_url) func.
    4.We copy the auth_code provided from our browser and store in the variable in "auth_code".
    5.Next we need to uncomment the function generate_access_token(auth_code, appId, app_secret, redirect_url).
    6.Then we need to make sure getauthToken(appId, redirect_url) func is commented.
    7.We run this module again with appropriate parameters.
    """
    # The provided redirct url while creating the app
    redirect_url = "http://127.0.0.1:8888/"

    # The app id we get after creating the app
    appId = "SIA1G***73-100"

    # Function to get the auth code and need to be commented while calling the generate_access_token(x,x,x) func.
    # getauthToken(appId, redirect_url)

    # The app secret we got after creating the app.
    app_secret = "DF**S5IK"

    # the genarted auth code we got from browser after running the getauthToken(x,x) func.
    auth_code = "*****************.eyJpc3MiOiJhcGkubG9naW4uZnllcnMuaW4iLCJpYXQiOjE3MjA2NzMwNjksImV4cCI6MTcyMDcwMzA2OSwibmJmIjoxNzIwNjcyNDY5LCJhdWQiOiJbXCJ4OjBcIiwgXCJ4OjFcIiwgXCJ4OjJcIiwgXCJkOjFcIiwgXCJkOjJcIiwgXCJ4OjFcIiwgXCJ4OjBcIl0iLCJzdWIiOiJhdXRoX2NvZGUiLCJkaXNwbGF5X25hbWUiOiJYTTAzNjk4Iiwib21zIjoiSzEiLCJoc21fa2V5IjoiYTRjZmQwMmFhNDM2NjliZDg2ZDZhZmJjNTdmZTRjNjUyZjAxYjkyYTAzMjlkOTQ2YTNmODE1NTEiLCJub25jZSI6IiIsImFwcF9pZCI6IlNJQTFHME1INzMiLCJ1dWlkIjoiMWU0MTMzYzQyZmU2NDE1YWEzOTk3NjhjYjkxY2Y3YTciLCJpcEFkZHIiOiIwLjAuMC4wIiwic2NvcGUiOiIifQ.LjlO2iJCf0sgvT8IAE4i8yXjbphsF8uwLTCC1hZY3Rc"

    # Function to get the access token and need to be commented while calling the getauthToken(x,x) func.
    print(generate_access_token(auth_code, appId, app_secret))


if __name__ == '__main__':
    main()
```

**Comment by SHIVANIUM-GIT** [comment]
"eyJpc3MiOiJhcGkubG9naW4uZnllcnMuaW4iLCJpYXQiOjE3MjA2NzMwNjksImV4cCI6MTcyMDcwMzA2OSwibmJmIjoxNzIwNjcyNDY5LCJhdWQiOiJbXCJ4OjBcIiwgXCJ4OjFcIiwgXCJ4OjJcIiwgXCJkOjFcIiwgXCJkOjJcIiwgXCJ4OjFcIiwgXCJ4OjBcIl0iLCJzdWIiOiJhdXRoX2NvZGUiLCJkaXNwbGF5X25hbWUiOiJYTTAzNjk4Iiwib21zIjoiSzEiLCJoc21fa2V5IjoiYTRjZmQwMmFhNDM2NjliZDg2ZDZhZmJjNTdmZTRjNjUyZjAxYjkyYTAzMjlkOTQ2YTNmODE1NTEiLCJub25jZSI6IiIsImFwcF9pZCI6IlNJQTFHME1INzMiLCJ1dWlkIjoiMWU0MTMzYzQyZmU2NDE1YWEzOTk3NjhjYjkxY2Y3YTciLCJpcEFkZHIiOiIwLjAuMC4wIiwic2NvcGUiOiIifQ.LjlO2iJCf0sgvT8IAE4i8yXjbphsF8uwLTCC1hZY3Rc"
this is your auth code

**Comment by rajasekhareee232** [comment]
Hi @tradewithmadhan @SHIVANIUM-GIT : This issue is still open i am facing same issue can some one help any work around mean while

**Comment by SHIVANIUM-GIT** [comment]
sure, what is the main issue you are facing ?

https://github.com/SHIVANIUM-GIT/fyer_api_websocket/blob/main/fyersacceskey.py
this is the file see this may be it will help

**Comment by rajasekhareee232** [comment]
@SHIVANIUM-GIT  yes, When running i am seeing below error:

{'s': 'error', 'code': -371, 'message': 'Please provide sha256 hash of appId and app secret'}

**Comment by SHIVANIUM-GIT** [comment]
did you use my code?

**Comment by rajasekhareee232** [comment]
Yes tried @SHIVANIUM-GIT  getting below error:

 line 6, in <module>
    from fyers_api.Websocket import ws
ModuleNotFoundError: No module named 'fyers_api.Websocket'

**Comment by SHIVANIUM-GIT** [comment]
Maybe I was using fyersV2.  You have to just according your fyers version

**Comment by rajasekhareee232** [comment]
I installed this @SHIVANIUM-GIT but still seeing error

pip install fyers-apiv2

**Comment by rajasekhareee232** [comment]
@SHIVANIUM-GIT : Again same issue with the script you shared :

{'s': 'error', 'code': -371, 'message': 'Please provide sha256 hash of appId and app secret'}

**Comment by SHIVANIUM-GIT** [comment]
Provide me the code for login which you wrote

**Comment by rajasekhareee232** [comment]
The same script you shared updated my client id and secreat key`from datetime import date
from fyers_api import fyersModel
from fyers_api import accessToken
import os
#from dotenv import load_dotenv

import datetime as dt
#load_dotenv()


client_id = os.getenv('client_id')
secret_key = os.getenv('secret_key')
redirect_uri = os.getenv('redirect_uri')
client_id = "VDOMNK3HR-100"
secret_key = "DNDCZG08FD"
redirect_uri = "https://trade.fyers.in/api-login/redirect-uri/index.html"
  

today = date.today().strftime("%Y-%m-%d")


def get_access_token():
    access = ""
    if not os.path.exists("./authcode"):
        print("Creating authcode directory")
        os.makedirs("./authcode")

    if not os.path.exists(f"authcode/{today}.txt"):
        session = accessToken.SessionModel(client_id=client_id, secret_key=secret_key,
                                           redirect_uri=redirect_uri, response_type="code", grant_type="authorization_code")
        response = session.generate_authcode()
        print("Login Url : ", response)
        auth_code = input("Enter Auth Code : ")
        session.set_token(auth_code)
        print(session.generate_token())
        access_token = session.generate_token()["access_token"]
        with open(f"authcode/{today}.txt", "w") as f:
            f.write(access_token)
    else:
        with open(f"authcode/{today}.txt", "r") as f:
            access = f.read()
    return access


access_token = get_access_token()

fyers = fyersModel.FyersModel(
    client_id=client_id, token=access_token, log_path=os.getcwd())

print(fyers.get_profile())
# print(fyers.funds())
# print(fyers.holdings())

# data = {"symbol": "NSE:NIFTYBANK-INDEX", "resolution": "5", "date_format": "1",
#         "range_from": "2023-01-17", "range_to": "2023-01-17", "cont_flag": "1"}

# print(fyers.history(data))


newToken = f"{client_id}:{access_token}"
symbol = ['NSE:NIFTYBANK-INDEX']
cws = ws.FyersSocket(access_token=newToken,
                     run_background=False, log_path=os.getcwd())


def on_ticks(msg):
    script = msg[0]['symbol']
    ltp = msg[0]['ltp']
    high = msg[0]['high_price']
    low = msg[0]['low_price']
    ltt = dt.datetime.fromtimestamp(msg[0]['timestamp'])
    print(
        f"Script:{script}  ,  ltp:{ltp}  ,  HIGH:{high} ,  LOW:{low},  ltt:{ltt}")


cws.websocket_data = on_ticks
cws.subscribe(symbol=symbol, data_type="symbolData")
cws.keep_running()
cws.unsubscribe(symbol=symbol)
`

**Comment by SHIVANIUM-GIT** [comment]
```bash
 
from datetime import date
from fyers_apiv3 import fyersModel
import os
from dotenv import load_dotenv
import datetime as dt
import json
load_dotenv()


client_id = os.getenv('client_id')
secret_key = os.getenv('secret_key')
redirect_uri = os.getenv('redirect_uri')

today = str(date.today())  

def get_access_token():
    access = ""
    
    if not os.path.exists("./authcode"):
        print("Creating authcode directory")
        os.makedirs("./authcode")

    auth_file = f"./authcode/{today}.json"  

    if not os.path.exists(auth_file):
        session = fyersModel.SessionModel(client_id=client_id, secret_key=secret_key,
                                          redirect_uri=redirect_uri, response_type="code", grant_type="authorization_code")
        response = session.generate_authcode()
        print("Login Url : ", response)
        auth_code = input("Enter Auth Code : ")
        session.set_token(auth_code)
        access_token = session.generate_token()["access_token"]

        auth_data = {
            "access_token": access_token
        }

        with open(auth_file, "w") as f:
            json.dump(auth_data, f)

    else:
        with open(auth_file, "r") as f:
            auth_data = json.load(f)
            access = auth_data.get("access_token", "")

    return access


access_token = get_access_token()

fyers = fyersModel.FyersModel(
    client_id=client_id, token=access_token, log_path=os.getcwd())

# print(fyers.funds())
# print(fyers.holdings())


data = {"symbol": "NSE:NIFTYBANK-INDEX", "resolution": "1", "date_format": "1",
        "range_from": "2023-01-17", "range_to": "2023-01-17", "cont_flag": "1"}

print(fyers.history(data))


# newToken = f"{client_id}:{access_token}"
# symbol = ['NSE:NIFTYBANK-INDEX','NSE:NIFTY50-INDEX']
# cws = ws.FyersSocket(access_token=newToken,
#                      run_background=False, log_path=os.getcwd())


# def on_ticks(msg):
#     script = msg[0]['symbol']
#     ltp = msg[0]['ltp']
#     high = msg[0]['high_price']
#     low = msg[0]['low_price']
#     close =msg[0]['close']
#     ltt = dt.datetime.fromtimestamp(msg[0]['timestamp'])
#     print(
#         f"Script:{script}  ,  ltp:{ltp}  ,  HIGH:{high} ,  LOW:{low},  ltt:{ltt}, close:{close}")


# cws.websocket_data = on_ticks
# cws.subscribe(symbol=symbol, data_type="symbolData")
# cws.unsubscribe(symbol=symbol)
# cws.keep_running()
# cws.close() 


```

**Comment by SHIVANIUM-GIT** [comment]
@rajasekhareee232 this is the code try this one you have to run  Two time

**Comment by rajasekhareee232** [comment]
@SHIVANIUM-GIT  i tried running the above script shared i am getting below error now:

RhNDY1ZWE3MGYzNzJjOWU3MTY3MGQiLCJpcEFkZHIiOiIwLjAuMC4wIiwic2NvcGUiOiIifQ.uPx6hwVnLkm2JvmF-8e96oFJQYlvtg2asPPtK8lRXb8
Traceback (most recent call last):
  File "C:/Users/DELL/Desktop/test_api_v3.py", line 51, in <module>
    access_token = get_access_token()
  File "C:/Users/DELL/Desktop/test_api_v3.py", line 34, in get_access_token
    access_token = session.generate_token()["access_token"]
KeyError: 'access_token'

**Comment by SHIVANIUM-GIT** [comment]
So, start from the beginning uninstall  all the set-up remove the library and reinstall all

**Comment by rajasekhareee232** [comment]
@SHIVANIUM-GIT  YES I DID it as checked still i am getting below error and it dint have access_token its throwing same error as above mentioned, Appreciated qucik resolution here

{'s': 'error', 'code': -371, 'message': 'Please provide sha256 hash of appId and app secret'}

**Comment by SHIVANIUM-GIT** [comment]
@rajasekhareee232   create the new repo and add me in it we will solve that on repo

**Comment by katmakhan** [comment]
have you migrated to v3?
